# fly.toml app configuration file generated for 18-0 on 2024-10-29T08:53:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'odoo-18'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8069
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

#[mounts]
#  source = "odoo"
#  destination = "/var/lib/odoo/filestore"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
